### ISSUE TITLE
このグループの名前

### ISSUE THREAD

**Issue by yasu80** [CIRKIT-withB/wholeissue#2]
このグループを名前ですけど,  一回生部屋というよりは学部生部屋ってことにしませんか?

学部生にしか関係ない話題をするところが微妙にないので...

settingsのprofileのdanger zone から変更できますが一応聞きたいと思って

**Comment by tanacchi** [comment]
CIRKIT-Beginnersはどうでしょうか

**Comment by tanacchi** [comment]
Bachelor （学部生）とBeginner（初心者）から
CIRKIT-withB にしました。
手元にあるリポジトリは一度消して`git clone`し直すことをおすすめします。
